@Possari.Web_HostAddress = http://localhost:5043
@ChildId = 4b0c9db5-33fe-4b10-b588-188cfe7c05c7
@RewardId = 2160fbfa-9641-47ba-9615-480b5022f799
@PendingRewardId = f95dcd26-76e2-4217-b9aa-704bf0112692

GET {{Possari.Web_HostAddress}}/children
Accept: application/json

###

GET {{Possari.Web_HostAddress}}/children/{{ChildId}}
Accept: application/json

###

DELETE {{Possari.Web_HostAddress}}/children/{{ChildId}}
Accept: application/json

###

POST {{Possari.Web_HostAddress}}/children
Accept: application/json
Content-Type: application/json

{
  "name": "A Child"
}

###

PATCH {{Possari.Web_HostAddress}}/children/{{ChildId}}
Accept: application/json
Content-Type: application/json

{
  "name": "The Child"
}

###

POST {{Possari.Web_HostAddress}}/children/{{ChildId}}/tokens/award
Accept: application/json
Content-Type: application/json

{
  "tokenAmount": 5
}

###

POST {{Possari.Web_HostAddress}}/children/{{ChildId}}/rewards/redeem
Accept: application/json
Content-Type: application/json

{
  "rewardId": "{{RewardId}}"
}

###

PATCH {{Possari.Web_HostAddress}}/children/{{ChildId}}/pending-rewards/{{PendingRewardId}}/receive
Accept: application/json
Content-Type: application/json
