@Possari.Web_HostAddress = http://localhost:5043
@RewardId = 2a788f76-3f6c-478d-84c0-d0ac5e7b5b5c

GET {{Possari.Web_HostAddress}}/rewards
Accept: application/json

###

GET {{Possari.Web_HostAddress}}/rewards/{{RewardId}}
Accept: application/json

###

DELETE {{Possari.Web_HostAddress}}/rewards/{{RewardId}}
Accept: application/json

###

POST {{Possari.Web_HostAddress}}/rewards
Accept: application/json
Content-Type: application/json

{
  "name": "A Reward",
  "tokenCost": 2
}

###

PATCH {{Possari.Web_HostAddress}}/rewards/{{RewardId}}
Accept: application/json
Content-Type: application/json

{
  "name": "The Reward",
  "tokenCost": 2
}

###
