@Possari.WebApi_HostAddress = http://localhost:5043
@ParentId = a2852759-9ae0-4c36-aa4d-06ad03a3e81e

GET {{Possari.WebApi_HostAddress}}/parents
Accept: application/json

###

GET {{Possari.WebApi_HostAddress}}/parents/{{ParentId}}
Accept: application/json

###

DELETE {{Possari.WebApi_HostAddress}}/parents/{{ParentId}}
Accept: application/json

###

POST {{Possari.WebApi_HostAddress}}/parents
Accept: application/json
Content-Type: application/json

{
  "name": "A Parent"
}

###

PATCH {{Possari.WebApi_HostAddress}}/parents/{{ParentId}}
Accept: application/json
Content-Type: application/json

{
  "name": "The Parent"
}

###
